### ISSUE TITLE
Mall TODO

### ISSUE THREAD

**Issue by iroflu** [Artamedes/ShadowlandsCustomServer#12]
Transmog NPC's (1 for each expac?)
- [ ] Spawned
- [ ] Transmogs added
____
- [x] Create custom Reputation: Shadow Militia
- [x] Create custom Reputation: Merchant Alliance
- [x] Create custom Reputation: Legion Assault Force (L.A.F.)
- [x] Create custom Reputation: Light Bringers
- [x] Create custom Reputation: Maw Opposition

- [x] Visions NPCs (for legendary weapons) should equip the weapon/item they give away)
- [x] Add NPCs wandering around
______________________________________________
NPCs to spawn:

Code Redeemer (redeem codes, such as winter giveaways, login first time codes, etc)
- [x] Spawned
- [ ] Scripted
___
Guild NPCs (approx 3 of them)
- [x] Spawned
- [x] Set proper info in DB to be registered as 'Guild' vendors
- [x] Fix Guild Vendor to properly show Guild Items in shop (npc_vendor to 800011)
- [x] Remove transmog flag from 800011 (Guild Vendor)
___
Shadow Militia Reputation NPC
- [x] Spawned
- [x] Scripted
___
Shadow Militia Recruiter (quests to find hidden Mall NPC's)
- [x] Spawned
- [x] Quests created
- [x] Scripted
________________________________________________
Hidden NPCs with quests to find:

- [x] Jon Bovi - Upgraded potions
- [x] Inkeeper Bokin (Crapopolis)
- [x] Quests above need to be scripted
- [x] Mount Tamer (Create quest from Mount Vender for first visit)
- [x] All these quests need text filled
