### ISSUE TITLE
Iron Docks TODO

### ISSUE THREAD

**Issue by iroflu** [Artamedes/ShadowlandsCustomServer#15]
Quest NPC:
Muzgonk (705015)
________

- [x] Iron Dock Workers (705007): (Majority of them throughout should look like they are "working" (.debug anim 234) (STATE_WORK_CHOPWOOD) - they will be equipped with hammers so it looks like they are repairing the siege equipment.

________

- [x] All 'Iron Archers' (705004) should be attacking the 'archery targets' in front of them.
- [x] First Iron Horde General (730621) (SpawnId: 1054663)
When player in range (probably far enough so as soon as player tele's into dungeon), he will say groupID(0) - while the archers are shooting
The Iron Horde Captains should clap (.debug anim 21) (ONESHOT_APPLAUD) after a few seconds (should clap several times since the animation is really short)
________
- [x] Iron Dock Overseer(1054847) / Iron Recruit(1052851):
Iron Recruit (730619) should say: groupID(0)
Iron dock overseer (705009): groupID(0) - he laughs after this (.debug anim 11) (ONESHOT_LAUGH)
Iron recruit cry emotes: (.debug anim 18) (ONESHOT_CRY) and then begs (.debug anim 20) (ONESHOT_BEG) and says groupID(1)
When players get in fairly close range (but not yet aggro), iron dock overseer says: groupID(1)
     -Iron recruit then auto-aggros
         -If players kill the Iron Recruit WITHOUT aggro'ing the iron dock overseer, he should laugh (.debug anim 11) (ONESHOT_LAUGH) and say groupID(2)
________
Marc and Parc:
- [x] If one aggro's, the other aggro's as well.
Upon aggro, their conversation starts:
Marc (705008) says: groupID(0)
Parc (730617) says: groupID(0)
Marc (705008) says:  groupID(1)
________
Second Iron Horde General: (730621):
- [x] The iron horde captains in each group should run in front of the iron recruits, both along same path, basically "getting the recruits in shape" etc
Iron horde general says: groupID(1)
Iron recruits (730619) have a chance to say "groupID(2)"
Iron Horde Captn (730620): groupID(0)
OR (small random chance to do either conversation)
Iron hrd captn says: groupID(1)
Iron recruit says: groupID(3)
________
Felloc:
- [x] He says on aggro: groupID(0)
________
War Elephant:
- [x] If players "activate" (or talk to it, idk yet) the Explosive Chicken, it will run over to the 2 siegemaker NPCs, blow them both up along with the nearby NPC's, causing the elephant to go on a rampage and kill all mobs within the shipping container section, before it ultimately crashes and kills itself.
The nearby NPCs will be looking at the siegmaker saying:
Iron dock ovrseer (705009) says: groupID(3)
Beastmster (730609) says: groupID(0)
2nd Beastmster says: groupID(1)
Iron dock oversr says: groupID(4)
Beastmaster says: groupID(2)
________
- [x] Unnamed Flesh Eater (set name later, the boss right after the shipping container sections) (730610)
Says when players get in semi-close but not aggro range: groupID(0)
Says on aggro: groupID(1)
________
- [x] Third Iron Horde General: (730621) (spawnid: 1054631)
Says when players in decent range: groupID(2)
Then says: groupID(3)
 - then both iron horde warlocks auto-aggro the players if they haven't already
 - if players aggro iron horde general, he says: groupID(4)
________
- [x] Slave area: (705012)
Quest will require player free at least 3 slave cages (ONLY THE ONES WITH SLAVES IN THEM - some are empty) (just opening them by right clicking)
If/When player opens the cage, one of the NPC's (all same entry, but just one chosen guid specifically) will say: groupID(0) - then run away a few steps and fade out
________
- [x] Shulloc (730613)
Says on aggro: groupID(0)
________
- [x] Fourth/Final Iron Horde General: (730621) (spawnid: 1054637):
Says when player in distance: groupID(5)
Then auto-aggros (or says on aggro) saying: groupID(6)w
    -Future implementation: Achievement-get if you kill him without any weapon equipped, titled "The Ol' One Two"
________
- [x] Skulloc (730612):
Says on when player in distance: groupID(0)
Auto-aggros and says/or says on aggro: groupID(1)
