### ISSUE TITLE
Mini M+ TODO

### ISSUE THREAD

**Issue by Artamedes** [Artamedes/ShadowlandsCustomServer#17]
Using the storyline dungeons create m+ modes

- [x] Challenge system need to be modify to be able to support more than one keystone.
- [x] 180653 is the second keystone and needs to be recognized as one. - need to update how challenge_key stores keys and savedata of m+ is coded bad in player object, must be a unique_ptr per each key
- [x] Affixes should be different
- [x] dungeons must all have bossAI and been set as boss in flags_extra
- [x] must implement dungeon chest loot
- [x] need a table for base scaling of dungeons, or something that overrides healthmodifier,dmgmodifier in m+ difficulty
- [x] new gear needs to drop from these dungeons
- [x] Need personal loot for gameobjects for the dunegon chest. Loot also needs to be generated by instancescript rather than Player::SendLoot
- [x] update all the dungeons to be maps from hotfixes and have modes Mythic and Mythic Keystone
- [x] generate scenario data for all dungs
- [x] Add all font of powers (.gob add 246779) to start of dungs
- [x] I experienced an issue where some challenges aren't complete after doing all the objectives.
- [x] Base scaling for all the dungeons
