### ISSUE TITLE
Dreadscar TODO

### ISSUE THREAD

**Issue by iroflu** [Artamedes/ShadowlandsCustomServer#20]
- [x] Add flying mobs waypoints

- [x] Demonic Tome (to the left upon spawn):  (703021)
 -Should not be clickable until both Hellfire Infernals are killed (SpawnID 1054294 and 1054293)
     -Players right click it to destroy book and get Anima
____

- [x] Kuryash Boss (703017):
On aggro says: groupID(0)
   -casts some big spell (find later)
       -casts this spell again at 30% health saying: groupID(1)
____
- [x] Bellatrix Boss (703013): 
On player nearby: groupID(0)
On aggro: groupID(1)
   -On aggro she summons 5 Necromantic Warriors (703018)
Has life draining spells
If Bellatrix is in combat with more than 1 player, Bellatrix has a chance to fully stun one player for a solid 10 seconds and says: groupID(2) whenever this happens.
Random chance to recast the summon 5 Necromantic Warriors (shouldnt be too high a chance)
____
- [x] Condemned Demons (703024) by the Larva pit, when players get in range:
1 demon (SpawnID 1054306) says: groupID(0)
The next demon (SpawnID 1054307) says: groupID(1)
____
- [x] Arcane Voidwalker (703011):
Says on aggro: groupID(0)
____
- [x] Moz'gar Mini-Boss (703009):
Says on aggro: groupID(0)
____
- [x] Dolgonir Boss (703012):
Says on player approach: groupID(0)
Says on aggro: groupID(1)
When he dies, he says: groupID(2)
Portal opens up to bring players to final boss area (preferably similar teleport style to Telogrus Rift portals)
    -teleports to .tele dreadscarfinal
____
- [x] Goroth Final Boss (703001):
On teleport: groupID(0)
On aggro: groupID(1)
Some form of channel spell (find later) should be cast by the 'Fel Conduit' (703027) constantly until dead - This channel spell keeps Goroth enranged
    -If players kill the Fel Conduit, Goroth will lose enrage status
    -If players do NOT kill the Fel Conduit, Goroth will not be able to die
         -When Goroth reaches 1 hp (with fel conduit still alive), he will say groupID(2)
