### ISSUE TITLE
Iro TODO

### ISSUE THREAD

**Issue by iroflu** [Artamedes/ShadowlandsCustomServer#32]
- [x] Create daily quests for Folnuna and Meto Invasion Points

- [x] Use SmartAI for this https://github.com/Artamedes/ShadowlandsCustomServer/issues/13

- [x] Add smartAI scripts for random NPCs in the mall to talk and stuff

- [x] Check for any missing waypoints/creature texts

- [x] Add Unit_Flag '33554432' to any NPC that should not be selectable (may have forgotten some of them
