### ISSUE TITLE
Early-Access TODO

### ISSUE THREAD

**Issue by iroflu** [Artamedes/ShadowlandsCustomServer#41]
Iro:
- [x] Fill in text for Reputation Commanders
- [x] Maybe equip weapons for dungeons https://github.com/Artamedes/ShadowlandsCustomServer/issues/33
- [x] Find any missing text, any incorrect text, etc.
- [x] Dungeon Defenders Scaling
___________________
Arta:
- [x] Scale ALL remaining dungeons - relating to this as well: https://github.com/Artamedes/ShadowlandsCustomServer/issues/17
- [x] Add reputation gains for each dungeon to related reputation (including quests)
- [x] Add item loot and currency loot to dungeons (Shadow essence from bosses, dungeon chests, etc)
- [x] https://github.com/Artamedes/ShadowlandsCustomServer/issues/23
___________________
Either:

- [x] Add pets to Pet Vendor in Mall (doesnt need to be much, just a few cool ones maybe)
