### ISSUE TITLE
Scaling TODO

### ISSUE THREAD

**Issue by iroflu** [Artamedes/ShadowlandsCustomServer#66]
This list included ALL scaling issues for every dungeon I noticed an issue. It (for now) only lists entire series/tiers, and no specific dungeon.

DO NOT ALTER ANY BOSSES HEALTH OR DAMAGE - THESE ARE PERFECTLY FINE WHERE THEY ARE.
_______
Maelstrom dungeons are at a nice easy spot, all 3 dungeons, so nothing required here.
_______
- [x] Legion dungeons need at least 5% reduced health as they take WAY too long to kill. (Their damage is completely fine, however.)
_______
- [x] Sanctuary of Light dungeons need health reduced by 7 (SEVEN)%. (Again, their damage is completely fine and should not be altered.)
- I originally wanted it reduced by 10% but after upgrading my weapon alone my damage went up by quite a bit, however not everyone will know to do this, or potentially not have the currency to do it right, so it should still be reduced, but not as much as originally thought.
_______
- [x] All of Mawsworn Dungeons should have health reduced by 7 (SEVEN)% - again, damage seems fine so don't touch that.
