### ISSUE TITLE
Mounttamer checklist

### ISSUE THREAD

**Issue by iroflu** [Artamedes/ShadowlandsCustomServer#89]
Refer to #9 for full explanation. Creating new issue as it would be insanely difficult to restructure the existing one.

Stages/Days:

- [ ] Day 1
- [ ] Day 2
- [ ] Day 3
- [ ] Day 4
- [ ] Final Day (5)
_________________________
Day 1: (npc mount size = .2 scale depending on how big/small the mount we choose is)

- [ ] Player chooses which mount they want from the tamer
- [ ] An egg is spawned at the 'temp egg' npc (WILL CREATE LATER, NOT CREATED AS OF NOW)
- [ ] Player "opens" the egg, tiny version of the mount "comes out" of the egg
- [ ] Player gets bucket of water and "pet food" quest items to feed the baby mount
- [ ] Mount Tamer says come back tomorrow (ends day 1 quests)
_________________________
Day 2: (npc mount size = .5)

- [ ] Mount tamer tells player to pet the baby mount (quest 2 start)
- [ ] Player "pets" the baby mount (uses closest looking player anim/emote to petting)
- [ ] Player then gets water/food for the baby mount and gives it to mount
- [ ] ends quest 2
_________________________
Day 3: (npc mount size = .8)

- [ ] Mount tamer says time to ride the mount (day 3 quest start)
- [ ] Player clicks the mount, sets up a set path vehicle system using the mount
- [ ] Player then gets food/water for it
- [ ] Mount tamer says "come back tomorrow to take your mount home" - ends day 3 quest
_________________________
Day 4: (npc mount size = 1, unless mount too big)

- [ ] Start quest 4
- [ ] Player gets last bit of food/water for the mount
- [ ] Player "pets" the mount
- [ ] Player talks to Mount Tamer who hands player the "reigns" to the mount, ending quest 4

_________________________
_________________________

Items to create:

- [ ] Bucket (Empty)
- [ ] Water Bucket
- [ ] Bundle of Pet Food
_________________________
NPC's to create:

- [ ] Egg npc (or object, depending on if we can find egg-cracked state for object or npc looks cracked when dead)
- [ ] Personal npc for the baby mount, using different model based on the chosen mount
- [ ] Bucket object - player clicks it to pick up a bucket quest item
- [ ] Water trough object - to fill the bucket, replaces bucket with water bucket
- [ ] Boxes object, player clicks to get pet food
