### ISSUE TITLE
Corruptions TODO

### ISSUE THREAD

**Issue by Artamedes** [Artamedes/ShadowlandsCustomServer#91]
Shadow: 760
Light: 320
Maw: 128

- [x] Step 1 Levels of corruption should replace the previous
- [x] Step 2 Depending on the corruption level, higher levels give more corruption, level 1 - 5 corruption, level 2 - 10 corruption, level 3 - 15 corruption
- [x] Step 3 - Implement all the corruption negative effect spells.
- [x] Step 4 - Implement a way to remove corruptions, (Corrupted Chisel - new item) - Give half of currency back
- [ ] Step 5 - Replace Currency Exchange to only buy transmog tokens and armor vouchers for anima
- [x] Step 6 - After previous steps are fixed. then we discuss the prices.
