### ISSUE TITLE
[Tracking Issue] Dragon Flight Status

### ISSUE THREAD

**Issue by BlackMetalz** [Artamedes/ShadowlandsCustomServer#99]
### Misc ###

- [x] Gossip

### Auth ###
- [x] Authentication / Login

### Ingame ###
- [x] Quests
- [x] Talents
- [ ] Battle Pet - wasn't impl in SL
- [x] BattlePay
- [x] Duel
- [x] Achievement
- [x] Explorer
- [ ] Transport - wasn't impl in SL
- [ ] Arena - wasn't impl in SL
- [ ] Battleground
- [ ] Dungeon Finder- wasn't impl in SL
- [ ] Raid Finder- wasn't impl in SL
- [ ] Instances
- [x] mmaps
